//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maize_Trade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int FarmerID { get; set; }
        public Nullable<decimal> MaizeWeight { get; set; }
        public Nullable<decimal> MaizeRate { get; set; }
        public Nullable<decimal> DeductionInWeight { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public byte[] Note { get; set; }
    
        public virtual Farmer Farmer { get; set; }
    }
}
