//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maize_Trade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int PartyID { get; set; }
        public Nullable<decimal> MaizeWeight { get; set; }
        public Nullable<decimal> MaizeRate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Note { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
